<?php
namespace W2w\Test\Apie\Controllers;

use erasys\OpenApi\Spec\v3\Document;
use erasys\OpenApi\Spec\v3\Info;
use PHPUnit\Framework\TestCase;
use W2w\Lib\Apie\Controllers\DocsController;
use W2w\Lib\Apie\OpenApiSchema\OpenApiSpecGenerator;
use Zend\Diactoros\Response\JsonResponse;

class DocsControllerTest extends TestCase
{
    public function testInvoke()
    {
        $specGenerator = $this->prophesize(OpenApiSpecGenerator::class);
        $specGenerator->getOpenApiSpec()
            ->shouldBeCalled()
            ->willReturn(new Document(
                new Info('Unittest', '1.0', "This spec is generated by a unit test"),
                []
            ));

        $item = new DocsController($specGenerator->reveal());

        $actual = $item();
        $this->assertInstanceOf(JsonResponse::class, $actual);
        $expected = [
            'openapi' => '3.0.1',
            'info' => [
                'title' => 'Unittest',
                'version' => '1.0',
                'description' => 'This spec is generated by a unit test'
            ],
            'paths' => []
        ];
        $this->assertEquals($expected, $actual->getPayload());
    }
}
